name = "burio-com"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
name = "burio-com"

[env.preview]
name = "burio-com-preview"
